parameters:
    file_input: '/app/input/input.txt'

services:
    client:
        class: App\CommissionCalculation\Infrastructure\Client\Client
        factory: ['App\CommissionCalculation\Infrastructure\Client\ClientFactory', create]
    parser:
        class: App\CommissionCalculation\Infrastructure\Parser\Parser
        arguments: ['@client']
    iterator:
        class: App\CommissionCalculation\Infrastructure\Reader\FileIterator
        arguments: ['%file_input%']
    reader:
        public: true
        class: App\CommissionCalculation\Infrastructure\Reader\Reader
        factory: ['App\CommissionCalculation\Infrastructure\Reader\ReaderFactory', 'make']
        arguments:
            - '@parser'
            - '@iterator'